# Generated by Django 3.0.10 on 2020-09-26 22:18

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('tweet_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=400)),
                ('truncated', models.BooleanField(default=False)),
                ('lang', models.CharField(blank=True, default=None, max_length=9, null=True)),
                ('user_id', models.BigIntegerField()),
                ('user_screen_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=150)),
                ('user_verified', models.BooleanField(default=False)),
                ('user_utc_offset', models.IntegerField(blank=True, default=None, null=True)),
                ('user_time_zone', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('favorite_count', models.PositiveIntegerField(blank=True, null=True)),
                ('retweet_count', models.PositiveIntegerField(blank=True, null=True)),
                ('user_followers_count', models.PositiveIntegerField(blank=True, null=True)),
                ('user_friends_count', models.PositiveIntegerField(blank=True, null=True)),
                ('in_reply_to_status_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('retweeted_status_id', models.BigIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
