# Generated by Django 3.0.10 on 2020-09-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='twitter_user_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='twitter_user_screen_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='twitteruserconfig',
            name='access_token',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='twitteruserconfig',
            name='oauth_token',
            field=models.CharField(max_length=400, verbose_name='Oauth Token'),
        ),
        migrations.AlterField(
            model_name='twitteruserconfig',
            name='oauth_token_secret',
            field=models.CharField(max_length=400, verbose_name='Oauth Token Secret'),
        ),
    ]
