# Generated by Django 3.0.10 on 2020-09-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20200928_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(),
        ),
    ]
