# Generated by Django 3.0.10 on 2020-09-26 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter', '0002_tweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user_id',
            new_name='twitter_user_id',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='user_name',
            new_name='twitter_user_name',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='user_screen_name',
            new_name='twitter_user_screen_name',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='user_verified',
            new_name='twitter_user_verified',
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
